### ISSUE TITLE
Pretty good attempt at routing!

### ISSUE THREAD

**Issue by eliascodes** [fac-17/ReactWeek-Martha-Georgia#16]
Eventually you'll take a look at something like `react-router` but [this](https://github.com/fac-17/ReactWeek-Martha-Georgia/blob/b9507cf52ba6bfc9443bcf88fa3232292e64b4da/src/App.js#L20-L39) is a good first stab. Might be an interesting exercise to see if you could think of a way to generalise what you have at the moment to allow you to pass an arbitrary number of routes to it.

**Comment by mkatenolan** [comment]
Thanks @eliascodes - good to know in the future!
